{{- if ne .chezmoi.os "windows" -}}
{{- if .external.zsh -}}
{{- if stat (joinPath .chezmoi.homeDir ".oh-my-zsh") -}}

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    exact = true
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    exact = true
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/git-open"]
    type = "git-repo"
    url = "https://github.com/paulirish/git-open.git"
    exact = true
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh_codex"]
    type = "git-repo"
    url = "https://github.com/tom-doerr/zsh_codex.git"
    exact = true
    refreshPeriod = "168h"

{{- end -}}
{{- end -}}
{{- end -}}
