
[window]
decorations = "Full"
opacity = 0.7
startup_mode = "Windowed"

[general]
import = [
    "~/.config/alacritty/profiles/common.toml",
    "~/.config/alacritty/fonts/fantasque_nf.toml",
    "~/.config/alacritty/keybindings/keybindings.toml",
]
