# ~/.config/sharship.toml
## Modified from https://starship.rs/presets/tokyo-night.html
add_newline = false

command_timeout = 2000

format = """
$shell\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[î‚´](bg:#769ff0 fg:#a3aed2)\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
$git_state\
$git_commit\
$git_metrics\
[î‚´](fg:#394260 bg:#212736)\
$CMake\
$c\
$python\
$nodejs\
$rust\
$golang\
$php\
$dotnet\
$java\
$lua\
[î‚´](fg:#212736 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\
$container\
$docker_context\
$conda\
$jobs\
$localip\
$cmd_duration\
$sudo \
\n\
$username$hostname\
$status\
$character"""

# $git_status\

[fill]
symbol = "â”€"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Vidwos" = "ó°•§ "
"Pictures" = "ï€¾ "
"Code" = "ï "
".config" = "î—¼ "
".vscode" = "ó°¨ "
".vs" = "ó°˜ "
".vim" = "îŸ… "

[status]
disabled = false
[username]
format = "[$user]($style):"
[hostname]
ssh_symbol = "ğŸŒ"
format = "[$hostname$ssh_symbol]($style)"

[git_branch]
symbol = "ï˜"
truncation_length = 8
truncation_symbol = ''
style = 'fg:bold purple bg:#394260'
format = '[on ](bg:#394260)[$symbol $branch(:$remote_branch) ]($style)'
ignore_branches = ['master', 'main']

[git_state]
style = "bg:#394260"
format = '[\($state( $progress_current of $progress_total)\) ]($style)'
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_commit]
style = "fg:bold green bg:#394260"
commit_hash_length = 6
format = '[\($hash$tag\)]($style)'

[git_status]
ignore_submodules = true
untracked = ""
style = "fg:bold yellow bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[git_metrics]
disabled = false
added_style = 'fg:bold green bg:#394260'
deleted_style = 'fg:bold red bg:#394260'
format = '[+$added]($added_style)[-$deleted]($deleted_style)'


[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'


# Customization

# languages
[c]
symbol = "î˜ "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
detect_extensions = ["c", "h", "cpp", "hpp"]
[lua]
symbol = "ó°¢± "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
[python]
style = "bg:#212736"
symbol = "ó°Œ  "
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# Prompt
[memory_usage]
disabled = false
threshold = 50
format = "using $symbol [${ram}( | ${swap})]($style) "
symbol = "ó°›"

[shlvl]
disabled = false
threshold = 1
symbol = "â†•ï¸ "

[shell]
disabled = false
bash_indicator = "î¯Š"
fish_indicator = 'ó°ˆº'
powershell_indicator = "î¯‡"
cmd_indicator = "î¯„"

[localip]
disabled = false
style = "yellow"
format = '@[$localipv4]($style)'

[os]
disabled = false
format = "$symbol"
symbols.Ubuntu = "î¯‰"
symbols.Windows = "î˜ª"

[sudo]
disabled = false
symbol = "ğŸ‘‘ "

# Conda
[conda]
disabled = false
ignore_base = false
format = "via [$symbol$environment]($style) "
